### ISSUE TITLE
Regression: FluidSynth linking

### ISSUE THREAD

**Issue by jwmatthys** [ccrma/chugins#22]
The FluidSynth chugin no longer works on Linux (and I think OSX too). After much frustrating bug hunting, I found that it's because the linker is called incorrectly. The reference to -lfluidsynth needs to be at the end of the linking command:

gcc -shared -lstdc++ -o FluidSynth.chug FluidSynth.o -lfluidsynth

Also, someone (me?) seems to have commented out part of the FluidSynth.cpp code...

I have it fixed in my fork and I could do a pull request but I have some other stuff in there that isn't ready for prime time...

**Comment by spencersalazar** [comment]
Weird. Would be great if you make a PR with fixes- you can probably `git cherry-pick` just the bug fixes to a separate branch, and make a PR from that branch.

**Comment by forrcaho** [comment]
I think this has been fixed, since I've been working with the FluidSynth chugin on Debian linux without any build issues.
